/*
 * generated by Xtext 2.23.0
 */
package de.andhub.example.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TodoDslRuntimeModule extends AbstractTodoDslRuntimeModule {
}
