/*
 * generated by Xtext 2.23.0
 */
package de.andhub.example.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.andhub.example.xtext.TodoDslRuntimeModule;
import de.andhub.example.xtext.TodoDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TodoDslIdeSetup extends TodoDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TodoDslRuntimeModule(), new TodoDslIdeModule()));
	}
	
}
