/*
 * generated by Xtext 2.23.0
 */
package de.andhub.example.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TodoDslUiModule extends AbstractTodoDslUiModule {

	public TodoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
